data:
  '1':
    ct: D:/Python/Viewer/example/H000282_0001.nii.gz
    pet: D:/Python/Viewer/example/H000282_0000.nii.gz
    type: NIfTI
label:
  '1':
    color: '#0800e7'
    name: Label 1
  '2':
    color: '#11ff00'
    name: Label 2
window:
  height: 826
  theme: dark
  width: 1160
